// website/src/components/InstallCommand.jsx
import {
  faBox,
  faCheck,
  faCopy,
  faDesktop,
  faTerminal
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useEffect, useState } from "react";

function InstallCommand() {
  const [selectedButton, setSelectedButton] = useState("linux");
  const [command, setCommand] = useState("Command unavailable");
  const [isCopied, setIsCopied] = useState(false);

  const copyToClipboard = () => {
    if (!isCopied) {
      navigator.clipboard.writeText(command);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
      window.plausible.trackEvent("install-command-copy", {
        props: { variant: selectedButton }
      }); // Track the command copying button clicks; the Plausible event name is "install-command-copy".
    }
  };

  useEffect(() => {
    const commands = {
      linux:
        'sudo bash -c "$(curl -fsSL https://downloads.ferronweb.org/install-v2.sh)"',
      windows:
        'powershell -c "irm https://downloads.ferronweb.org/install-v2.ps1 | iex"',
      docker:
        "docker pull ferronserver/ferron:2 && docker run --name myferron -d -p 80:80 --restart=always ferronserver/ferron:2"
    };

    setCommand(commands[selectedButton]);
  }, [selectedButton]);

  return (
    <div className="w-full rounded-lg border border-muted/60 bg-card/60 backdrop-blur-sm shadow-lg overflow-hidden">
      <div className="flex border-b border-muted/60 overflow-x-auto">
        <button
          className={`inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 ${selectedButton === "linux" ? "bg-primary text-primary-foreground" : ""} shadow hover:bg-primary/90 rounded-none border-r border-muted/60 py-2 px-4 h-12 cursor-pointer`}
          onClick={() => setSelectedButton("linux")}
        >
          <FontAwesomeIcon icon={faTerminal} className="mr-2 h-4 w-4" />
          GNU/Linux
        </button>
        <button
          className={`inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 ${selectedButton === "windows" ? "bg-primary text-primary-foreground" : ""} shadow hover:bg-primary/90 rounded-none border-r border-muted/60 py-2 px-4 h-12 cursor-pointer`}
          onClick={() => setSelectedButton("windows")}
        >
          <FontAwesomeIcon icon={faDesktop} className="mr-2 h-4 w-4" />
          Windows Server
        </button>
        <button
          className={`inline-flex items-center justify-center whitespace-nowrap text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 ${selectedButton === "docker" ? "bg-primary text-primary-foreground" : ""} shadow hover:bg-primary/90 rounded-none border-r border-muted/60 py-2 px-4 h-12 cursor-pointer`}
          onClick={() => setSelectedButton("docker")}
        >
          <FontAwesomeIcon icon={faBox} className="mr-2 h-4 w-4" />
          Docker
        </button>
      </div>
      <div className="bg-secondary/50 p-4 relative">
        <pre className="text-sm sm:text-base overflow-x-auto p-2 rounded-md bg-muted/30">
          <code className="text-foreground">{command}</code>
        </pre>
        <button
          className="bg-secondary/50 inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 hover:bg-accent absolute top-5 right-5 h-8 w-8 text-muted-foreground hover:text-foreground cursor-pointer"
          onClick={copyToClipboard}
        >
          <FontAwesomeIcon
            icon={!isCopied ? faCopy : faCheck}
            className="w-4 !h-4"
          />
          <span className="sr-only">Copy code</span>
        </button>
      </div>
    </div>
  );
}

export default InstallCommand;

// website/src/components/landing/InstallCommand.svelte
<script lang="ts">
  import { type IconProp } from "@fortawesome/fontawesome-svg-core";
  import {
    faBox,
    faCheck,
    faCopy,
    faDesktop,
    faTerminal
  } from "@fortawesome/free-solid-svg-icons";
  import { FontAwesomeIcon } from "@fortawesome/svelte-fontawesome";

  interface Platform {
    id: string;
    name: string;
    command: string;
    icon: IconProp;
  }

  const platforms: Platform[] = [
    {
      id: "linux",
      name: "GNU/Linux",
      command: 'sudo bash -c "$(curl -fsSL https://get.ferron.sh/v2)"',
      icon: faTerminal
    },
    {
      id: "windows",
      name: "Windows Server",
      command: 'powershell -c "irm https://get.ferron.sh/v2-win | iex"',
      icon: faDesktop
    },
    {
      id: "docker",
      name: "Docker",
      command:
        "docker pull ferronserver/ferron:2 && docker run --name myferron -d -p 80:80 --restart=always ferronserver/ferron:2",
      icon: faBox
    }
  ];

  let currentPlatformIndex = $state(0);
  let command = $derived(platforms[currentPlatformIndex].command);
  let isCopied = $state(false);

  $effect(() => {
    if (isCopied) {
      setTimeout(() => {
        isCopied = false;
      }, 2000);
    }
  });
</script>

<div
  class="w-full rounded-lg border border-muted/60 bg-card/60 backdrop-blur-sm shadow-lg overflow-hidden text-start"
>
  <div class="flex border-b border-muted/60 overflow-x-auto">
    {#each platforms as platform, platformIndex}
      <button
        class="btn hover:bg-primary/90 hover:text-primary-foreground rounded-none border-r border-muted/60 py-2 px-4 h-12"
        class:bg-primary={platformIndex === currentPlatformIndex}
        class:text-primary-foreground={platformIndex === currentPlatformIndex}
        class:bg-inherit={platformIndex !== currentPlatformIndex}
        class:text-inherit={platformIndex !== currentPlatformIndex}
        onclick={() => (currentPlatformIndex = platformIndex)}
      >
        <FontAwesomeIcon icon={platform.icon} class="mr-2 size-4" />
        {platform.name}
      </button>
    {/each}
  </div>

  <div class="bg-secondary/50 p-4">
    <div class="bg-muted/30 rounded-md flex">
      <pre
        class="text-sm sm:text-base overflow-x-auto p-2 grow self-center"
      ><code class="text-foreground">{command}</code></pre>
      <button
        class="btn p-0 bg-secondary/50 hover:bg-accent size-7 min-w-7 sm:h-8 sm:w-8 sm:min-w-8 m-1 text-muted-foreground hover:text-accent-foreground cursor-pointer"
        onclick={async () => {
          navigator.clipboard.writeText(command);
          isCopied = true;

          // Track the command copying button clicks; the Plausible event name is "install-command-copy".
          // Had to use dynamic imports, since the Plausible tracker module doesn't resolve in SSR.
          (await import("@plausible-analytics/tracker")).track("install-command-copy", {
            props: { variant: platforms[currentPlatformIndex].id }
          });
        }}
      >
        {#if isCopied}
          <FontAwesomeIcon icon={faCheck} class="size-4!" />
        {:else}
          <FontAwesomeIcon icon={faCopy} class="size-4!" />
        {/if}
        <span class="sr-only">Copy code</span>
      </button>
    </div>
  </div>
</div>
